version: '3.7'

services:
  api2:
    build:
      context: .
    expose:
      - 3090
    restart: always
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Moscow

networks:
  default:
    external: true
    name: evilcorp
